version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
  docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: image
          command: |
            TAG=latest
            IMAGE=depth-app
            docker build -t $IMAGE:$TAG .
            docker login $REGISTRY_URI -u $REGISTRY_USER -p $REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $REGISTRY_URI/$IMAGE:$TAG
            docker push $REGISTRY_URI/$IMAGE:$TAG
workflows:
  version: 2
  cd:
    jobs:
      - build
      - docker-image:
          filters:
            branches:
              only: master
          requires:
            - build